# Includes the standard and recommended lints for Flutter projects.
# For more information, see: https://flutter.dev/docs/testing/analysis-options
include: package:flutter_lints/flutter.yaml

# Custom rules to enforce higher code quality and a stricter style.
linter:
  rules:
    # ===== Style & Readability Rules =====

    # Enforce using single quotes for strings for a consistent code style.
    - prefer_single_quotes: true

    # For better readability, places `child` or `children` properties last in widget constructors.
    - sort_child_properties_last: true
    
    # Ensures the @override annotation is used when overriding methods.
    - annotate_overrides: true

    # ===== Performance & Best Practices =====

    # Encourage using const for constructors where possible for better performance.
    - prefer_const_constructors: true

    # Encourage using const for immutable collection literals.
    - prefer_const_literals_to_create_immutables: true
    
    # Encourage using `final` for local variables that are not reassigned.
    - prefer_final_locals: true

    # ===== Code Cleanup & Error Prevention =====

    # Avoid using `print()` in production code; use a proper logger instead.
    - avoid_print: true

    # Avoid functions that are unnecessarily marked as `async`.
    - unnecessary_async: true
    
    # Cleans up code by avoiding arguments passed with their default values.
    - avoid_redundant_argument_values: true

    # Enforce documentation for all public API members.
    # This helps ensure the package is well-documented and gets a high pub.dev score.
    - public_member_api_docs: true